title:              H.J Blog
email:              hwangjun9349@gmail.com
description:        4년차 웹개발자 입니다. 목표 : 1일 1회 커밋!!
author:             Hwang Jun
baseurl:            "/"
url:                "https://hwangjun.github.io"

# Social Profiles
twitter_username:   
github_username:    hwangjun
facebook_username:  junko61
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:  UA-155387702-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
